Fix SHA-1 hashing, update style
google/macops-planb pull request #7
Opened 2017-05-30 20:48 UTC by russellhancox

2017-06-08 16:28 UTC, tburgin requested changes

2017-06-08 16:28 UTC, tburgin commented on planb/PBPackageInstaller.m
>      _receiptName = receiptName;
Since this line accesses the NSString object directly, manually copy: [receiptName copy]
Same for the other two.

2017-06-08 16:28 UTC, tburgin commented on planb/PBPackageInstaller.m
> +@property(nonatomic, copy) NSString *packagePath;
Are these three being set anywhere besides init? If not: (readonly, nonatomic)

2017-06-08 16:28 UTC, tburgin commented on planb/PBPackageInstaller.m
> +@property(nonatomic, copy) NSString *receiptName;
nit: can you declare this property before packagePath. That way it matches the order or the arguments for the init method below.

2017-06-08 16:28 UTC, tburgin commented on planb/PBPackageInstaller.m
> +          [self SHA1ForFileAtPath:self.packagePath],
Is this the only time SHA1ForFileAtPath: is called with self.packagePath? If not, consider caching the hash.

2017-06-08 16:28 UTC, tburgin commented on planb/PBPackageInstaller.m
> +  CC_SHA1([fileData bytes], (unsigned int)[fileData length], sha1);
Dot syntax. Cast fileData.length as CC_LONG.
CC_SHA1(fileData.bytes, (CC_LONG)fileData.length, sha1);

2017-06-08 16:28 UTC, tburgin commented on planb/PBPackageInstaller.m
> +    [buf appendFormat:@"%02x", (unsigned char)sha1[i]];
sha1[i] is already an unsigned char, no need to cast it.

2017-06-09 20:28 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +    [buf appendFormat:@"%02x", (unsigned char)sha1[i]];
Bad copy & paste. Done.

2017-06-09 20:28 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +  CC_SHA1([fileData bytes], (unsigned int)[fileData length], sha1);
Done

2017-06-09 20:28 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +          [self SHA1ForFileAtPath:self.packagePath],
Yes it is.

2017-06-09 20:28 UTC, russellhancox commented on planb/PBPackageInstaller.m
>      _receiptName = receiptName;
Done

2017-06-09 20:28 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +@property(nonatomic, copy) NSString *receiptName;
Done

2017-06-09 20:28 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +@property(nonatomic, copy) NSString *packagePath;
Nope and done

2017-06-09 20:46 UTC, tburgin requested changes

2017-06-09 20:46 UTC, tburgin commented on planb/PBPackageInstaller.m
> +  CC_SHA1([fileData bytes], (unsigned int)[fileData length], sha1);
s/(unsigned int)/(CC_LONG)

2017-06-09 20:46 UTC, tburgin commented on planb/PBPackageInstaller.m
> +    [buf appendFormat:@"%02x", (unsigned char)sha1[i]];
The cast still appears for me?

2017-06-12 14:41 UTC, tburgin approved these changes

2017-06-12 14:42 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +  CC_SHA1([fileData bytes], (unsigned int)[fileData length], sha1);
_grumble_

2017-06-12 14:42 UTC, russellhancox commented on planb/PBPackageInstaller.m
> +    [buf appendFormat:@"%02x", (unsigned char)sha1[i]];
Looking at outdated commit? See [here](https://github.com/google/macops-planb/pull/7/commits/9c2c221ad41d1326de47bc73fb021835ecb1cf12#diff-75a6e127cb6650fa72f8036592199f72L251)

2017-06-12 14:42 UTC, merged